language: python
dist: xenial
python:
- 3.7
- 3.6
- 3.5
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    repo: molssi-seamm/seamm
    tags: true
  user: seamm
  password:
    secure: cr96T65UCkPPe6qGbKIJNBqDFA4ZvIdbsEM2on4+yvf9pAQDEmmWyiL4LDPVnpvqedYG0ki8TlERq3cAwsoEBkdI/skJDVAUbO7da/cJhDxOVBat0i9jR2c+W53hF1HYCBcOX9UuYmDqjw7FDnzOz0paUytKOR3h1PJUFGlH46Nl4XwxkiWjETvi2vmfzZtFZMdjAprC5dw05J8OVZnC/JygKttKkpFq3+8V8xexwns64bryz5+A9DLkiStAXZp9pyiu+y5WDfld9aXDiv8/3Uf5MnSuktlGGYyIpWOx2WJMkMl8S2fbIfoHZhVcUZhYFb4tTUBk96JGqyzOgoBi4evtBJbzLXngK0wNsAPRsZ+5ZW6MdWZKgATlI/UpNtLStfeBTU/G+TCtvv9GJEZ3kxUgW35CvyImhd9/XQgjw4eguilz4EpgasWzA+yYK3rXkj26WO76xsfWV5+4Oe0TFRuPGuNjA/Mq2je2TcBwp3WAQ0aekXJcVzLodTeCZVUoPrC5Dgaro62JfOozXXAQFe0JJtVrGyosi5U2rCfJpZOG32Un7ZsLJYYU3+ZNVPUkmyHZhxLpCYOfhQYUirarHvXmrDiF0EGckH3gSeTJVyiRzyrmYTrWXd83hxep3c21nOdFsoJzhltPgm9fgL17LX2Do4DUuUzG1QqYWczbNTI=
matrix:
  fast_finish: true
stages:
- lint
- check
- test
install:
- pip install -U tox-travis
- pip install -U codecov
jobs:
  include:
  - stage: lint
    script: tox -e lint
    python: '3.6'
script: tox -e coverage
after_success:
- codecov -e TOX_ENV
